feat: allow to specify static IP addresses
hwdsl2/docker-ipsec-vpn-server pull request #277
Opened 2022-02-12 00:51 UTC by wolasss

This PR introduces optional static IP addresses that work both in l2tp and ipsec-xauth. 

This feature request has been brought up many times: https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/32, https://github.com/hwdsl2/docker-ipsec-vpn-server/pull/222 https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/159 https://github.com/hwdsl2/setup-ipsec-vpn/issues/508

This feature is very much needed as one cannot easily build own Dockerfile based on this image because all of the configurations are done in `run.sh` script that is being run on CMD. Therefore, in the child Dockerfile, it is impossible to extend this configuration script - one has to copy the whole repository which is a hassle (for instance keeping it up to date).

With this PR, the user can specify `VPN_ADDL_IP_ADDRS` in addition to `VPN_ADDL_USERS` and `VPN_ADDL_PASSWORDS`. It works the same, for example:

```
VPN_ADDL_USERS=adduser1 adduser2 adduser3
VPN_ADDL_PASSWORDS=test1 test2 test3
VPN_ADDL_IP_ADDRS=192.168.42.3 192.168.42.4
```

`adduser1` will be assigned 192.168.42.3, `adduser2` is assigned 192.168.42.4 and `adduser3` is assigned a dynamic IP address from the pool.  Note, that the users with dynamic IP addresses should be stated at the end of the list (this should be stated in the docs). 

Please let me know what do you think if you like it I can:

1) possibly add the same feature with IKEv2
2) add `VPN_ADDL_IP_ADDRS` parameter validation  
3) update the documentation to cover this and explain the limitations (such that a user by default could specify 42.2-42.9 address or adjust VPN_L2TP_POOL accordingly)

2022-02-12 20:09 UTC, hwdsl2 requested changes
@wolasss Thank you for contributing! I've added a few review comments. Allowing to specify static IP addresses is a nice idea, although it may take efforts to implement it correctly with the right documentation. Your comments about the parameter validation and limitations make sense, as those are some of the areas to consider.

Regarding static IP addresses for IKEv2 mode, unfortunately it is not straightforward to do, and could be part of future work. See advanced usage [1] for some additional information.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic

2022-02-17 01:46 UTC, hwdsl2 commented
@wolasss I found an issue with this approach: The static IPs for IPsec/XAuth mode should be different than that for IPsec/L2TP mode. The former should be in the range 192.168.43.1-192.168.43.9, while the latter should be within 192.168.42.2-192.168.42.9. Therefore this PR may need more thoughts or changes to work.

2022-02-17 22:13 UTC, wolasss commented
@hwdsl2 

Hey, yes I thought about that but since there is routing between those two networks that should not be a problem in my opinion. A user can decide in which network he wants to assign a static IP address, and it will be reachable from both cisco and l2tp users. The same limitations apply that it must be outside of pool IP address in both networks though.

2022-02-18 03:22 UTC, hwdsl2 commented
@wolasss The IPTables FORWARD and NAT rules [1] have specific rules for each internal network `192.168.42.0/24` and `192.168.43.0/24`. For example, assigning an IPsec/XAuth VPN client a static IP such as `192.168.42.2` doesn't work, because the IPTables MASQUERADE rule for IPsec/XAuth [2] excludes IPsec traffic, but the rule for IPsec/L2TP [3] does not. As a result, in this example `192.168.42.2` cannot communicate with the `192.168.43.0/24` network. There are similar restrictions in the FORWARD rules.

So in conclusion, static IPs for IPsec/L2TP mode and IPsec/XAuth mode probably need to be separately specified.

An alternative approach is to instead specify the username(s) that needs to be assigned static IPs (e.g. `VPN_STATIC_IP_USERS`, if the user does not care which IPs are assigned. For example, the first username in that list gets assigned `192.168.42.2` and `192.168.43.2` for IPsec/L2TP and IPsec/XAuth mode, respectively. Not sure if this is what users want, just something to consider.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/c4d40685071b03652d835c31b40aa464abeda97a/run.sh#L496-L511
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/c4d40685071b03652d835c31b40aa464abeda97a/run.sh#L510
[3] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/c4d40685071b03652d835c31b40aa464abeda97a/run.sh#L511

2022-03-03 12:31 UTC, wolasss commented
@hwdsl2 thank you for your detailed explanation. 

Well, the alternative approach where static IPs are assigned 'automatically' did not convince me because it gives the user (administrator) much less control. 

Apart from the two separate `VPN_ADDL_IP_ADDRS` lists, I see another alternative solution: 

We could leave this as is, and explain in the documentation, that a user (admin) needs to specify the correct IP for the static VPN client depending on how the client connects to the VPN. The reasoning is that because it is a static client and the client connection is configured only once, therefore the admin responsibility may be to choose the appropriate connection method (l2tp or xauth) and assign the correct IP address accordingly. I think it leaves the configuration as simple as it is now with minimal overhead for the admin to choose a connection method for each static IP one assigns, but from my perspective it is totally acceptable. 

What do you think?

2022-03-04 04:59 UTC, hwdsl2 approved these changes

2022-03-04 04:59 UTC, hwdsl2 commented
@wolasss Thanks for sharing your thoughts. I agree with you on keeping this simple for now. I'll merge this as is and do some minor cleanups. One possible future improvement could be to identify which subnet the static IP belongs to, and only assign static IP for that specific mode (e.g. IPsec/L2TP), while keep the user's IP for the other mode (e.g. IPsec/XAuth) auto-assigned.

2022-03-04 05:00 UTC, merged